INSERT INTO public.consultation_dossiers (id, project_name, category, title, pdf_url)
VALUES
  (201, 'Voie Lyonnaise 1 - Nord (Boulevard du 11 Novembre / Avenue Einstein)', 'velo', 'Dossier de concertation VL1 Nord - 11 Novembre & Einstein', 'https://cyclopolis.lavilleavelo.org/vl1/VL1Nord_11Nov_Einstein.pdf'),
  (202, 'Voie Lyonnaise 1 - Centre (Tête d''Or à Halle Tony Garnier)', 'velo', 'Dossier de concertation VL1 Centre - Tête d''Or à Halle Tony Garnier', 'https://cyclopolis.lavilleavelo.org/vl1/VL1Centre_TetedOr_HalleGarnier.pdf'),
  (203, 'Voie Lyonnaise 2 - Centre (Pont Poincaré – Avenue Berthelot)', 'velo', 'Dossier de concertation VL2 Centre - Poincaré à Berthelot', 'https://cyclopolis.lavilleavelo.org/vl2/VL2Centre_Poincaré_Berthelot.pdf'),
  (204, 'Voie Lyonnaise 2 - Sud (Berthelot – Saint-Priest)', 'velo', 'Dossier de concertation VL2 Sud - Berthelot à Saint-Priest', 'https://cyclopolis.lavilleavelo.org/vl2/VL2Sud_Berthelot_St-Priest.pdf'),
  (205, 'Voie Lyonnaise 3 - Nord (Quincieux/Genay – Île Barbe)', 'velo', 'Dossier de concertation VL3 Nord - Quincieux/Genay à Île Barbe', 'https://cyclopolis.lavilleavelo.org/vl3/VL3Nord_IleBarbe_Quincieux.pdf'),
  (206, 'Voie Lyonnaise 3 - Centre (Île Barbe – Pont Kitchener)', 'velo', 'Dossier de concertation VL3 Centre - Île Barbe à Pont Kitchener', 'https://cyclopolis.lavilleavelo.org/vl3/VL3Centre_Ile%20Barbe_Pont%20Kitchener.pdf'),
  (207, 'Voie Lyonnaise 3 - Centre (Quai Jean‑Jacques Rousseau)', 'velo', 'Dossier de concertation VL3 Centre - Quai Jean‑Jacques Rousseau', 'https://cyclopolis.lavilleavelo.org/vl3/VL3Centre_QuaiJJRousseau.pdf'),
  (208, 'Voie Lyonnaise 3 - Sud (Pont Mulatière – barrage CNR)', 'velo', 'Dossier de concertation VL3 Sud - Pont Mulatière à barrage CNR', 'https://cyclopolis.lavilleavelo.org/vl3/VL3Sud_Pont%20Mulati%C3%A8re_Barrage%20CNR.pdf'),
  (209, 'Voie Lyonnaise 3 - ViaRhôna (Irigny – Givors)', 'velo', 'Dossier de concertation VL3 ViaRhôna - 2019', 'https://cyclopolis.lavilleavelo.org/vl3/VL3_ViaRhona_201906.pdf'),
  (210, 'Voie Lyonnaise 4 - Nord (Lissieu – La Garde)', 'velo', 'Dossier de concertation VL4 Nord - Lissieu à La Garde', 'https://cyclopolis.lavilleavelo.org/vl4/VL4Nord_Lissieu_La%20Garde.pdf'),
  (211, 'Voie Lyonnaise 4 - Nord (La Garde – Porte de Vaise)', 'velo', 'Dossier de concertation VL4 Nord - La Garde à Porte de Vaise', 'https://cyclopolis.lavilleavelo.org/vl4/VL4Nord_La%20Garde_Porte%20de%20Vaise.pdf'),
  (212, 'Voie Lyonnaise 4 & 5 - Vaise', 'velo', 'Dossier de concertation commun VL4 & VL5 - Vaise', 'https://cyclopolis.lavilleavelo.org/vl4/VL4VL5_Vaise.pdf'),
  (213, 'Voie Lyonnaise 4 - Centre (Pont Clémenceau – Duquesne)', 'velo', 'Dossier de concertation VL4 Centre - Pont Clémenceau à Duquesne', 'https://cyclopolis.lavilleavelo.org/vl4/VL4Centre_PontCl%C3%A9menceau_Duquesne.pdf'),
  (214, 'Voie Lyonnaise 4 - Est (Verguin – Flachet)', 'velo', 'Dossier de concertation VL4 Est - Verguin à Flachet', 'https://cyclopolis.lavilleavelo.org/vl4/VL4Est_Verguin_Flachet.pdf'),
  (215, 'Voie Lyonnaise 5 - Est (Poincaré – Bron Aéroport)', 'velo', 'Dossier de concertation VL5 Est - Poincaré à Bron Aéroport', 'https://cyclopolis.lavilleavelo.org/vl5/VL5Est_Poincaré_Bron%20A%C3%A9roport.pdf'),
  (216, 'Voie Lyonnaise 5 - Oullins', 'velo', 'Dossier de concertation VL5 - Oullins', 'https://cyclopolis.lavilleavelo.org/vl5/VL5_Oullins.pdf'),
  (217, 'Voie Lyonnaise 6 - Nord (Herbouville – Crépieux)', 'velo', 'Dossier de concertation VL6 Nord - Herbouville à Crépieux', 'https://cyclopolis.lavilleavelo.org/vl6/VL6Nord_Herbouville_Crepieux.pdf'),
  (218, 'Voie Lyonnaise 6 - Rive Droite (Pont de Lattre – Pont Gallieni)', 'velo', 'Dossier de concertation VL6 - Rive Droite', 'https://cyclopolis.lavilleavelo.org/vl6/VL6_RiveDroite_Concertation.pdf'),
  (219, 'Voie Lyonnaise 6 - Oullins', 'velo', 'Dossier de concertation VL6 - Oullins', 'https://cyclopolis.lavilleavelo.org/vl6/VL6_Oullins.pdf'),
  (220, 'Voie Lyonnaise 6 - Saint-Genis-Laval', 'velo', 'Dossier de concertation VL6 - Saint‑Genis‑Laval', 'https://cyclopolis.lavilleavelo.org/vl6/VL6_St-Genis-Laval.pdf'),
  (221, 'Voie Lyonnaise 7 - Nord (Rillieux-la-Pape – Caluire – Croix-Rousse)', 'velo', 'Dossier de concertation VL7 Nord - Rillieux à Croix‑Rousse', 'https://cyclopolis.lavilleavelo.org/vl7/VL7Nord_Rillieux_Caluire_CroixRousse.pdf'),
  (222, 'Voie Lyonnaise 7 - Centre (Pont Churchill – Garibaldi)', 'velo', 'Dossier de concertation VL7 Centre - Pont Churchill à Garibaldi', 'https://cyclopolis.lavilleavelo.org/vl7/VL7Centre_PontChurchill_Garibaldi.pdf'),
  (223, 'Voie Lyonnaise 7 - Garibaldi phase 3 (Arménie – Gde Rue de la Guillotière)', 'velo', 'Dossier de concertation VL7 - Garibaldi phase 3', 'https://cyclopolis.lavilleavelo.org/vl7/VL7Garibaldi_phase3.pdf'),
  (224, 'Voie Lyonnaise 7 - Sud (Garibaldi – Lyon 7 – Saint-Fons)', 'velo', 'Dossier de concertation VL7 Sud - Garibaldi (Lyon 7) à Saint‑Fons', 'https://cyclopolis.lavilleavelo.org/vl7/VL7Sud_GaribaldiLyon7_St-Fons.pdf'),
  (225, 'Voie Lyonnaise 7 - Yves Farge (Saint-Fons – Feyzin)', 'velo', 'Dossier de concertation VL7 - Boulevard Yves Farge', 'https://cyclopolis.lavilleavelo.org/vl7/VL7YvesFarge_BUE.pdf'),
  (226, 'Voie Lyonnaise 8 - Nord (Charbonnières-les-Bains)', 'velo', 'Dossier de concertation VL8 Nord - Charbonnières-les-Bains', 'https://cyclopolis.lavilleavelo.org/vl8/VL8Nord_Charbonni%C3%A8res.pdf'),
  (227, 'Voie Lyonnaise 8 - Nord (La Tour de Salvagny – Tassin Valvert)', 'velo', 'Dossier de concertation VL8 Nord - La Tour de Salvagny à Tassin Valvert', 'https://cyclopolis.lavilleavelo.org/vl8/VL8Nord_La%20Tour%20de%20Salvagny_Tassin%20Valvert.pdf'),
  (228, 'Voie Lyonnaise 8 - Ouest (Tassin – Buyer)', 'velo', 'Dossier de concertation VL8 Ouest - Tassin à Buyer', 'https://cyclopolis.lavilleavelo.org/vl8/VL8Ouest_Tassin_Buyer.pdf'),
  (229, 'Voie Lyonnaise 8 - Centre (Perrache – Mermoz)', 'velo', 'Dossier de concertation VL8 Centre - Perrache à Mermoz', 'https://cyclopolis.lavilleavelo.org/vl8/VL8Centre_Perrache_Mermoz.pdf'),
  (230, 'Voie Lyonnaise 8 - Est (Mermoz – Bron Porte des Alpes)', 'velo', 'Dossier de concertation VL8 Est - Mermoz à Bron Porte des Alpes', 'https://cyclopolis.lavilleavelo.org/vl8/VL8Est_Mermoz_Bron%20Porte%20des%20Alpes.pdf'),
  (231, 'Voie Lyonnaise 9 - Passerelle Oullins – Gerland', 'velo', 'Dossier de concertation VL9 - Passerelle Oullins-Gerland', 'https://cyclopolis.lavilleavelo.org/vl9/VL9Passerelle_Oullins_Gerland.pdf'),
  (232, 'Voie Lyonnaise 9 - Est (Jonage – Villeurbanne St‑Jean)', 'velo', 'Dossier de concertation VL9 Est - Jonage à Villeurbanne St‑Jean', 'https://cyclopolis.lavilleavelo.org/vl9/VL9Est_Jonage_Villeurbanne%20St-Jean.pdf'),
  (233, 'Voie Lyonnaise 10 - Meyzieu – Part-Dieu', 'velo', 'Dossier de concertation VL10 - Meyzieu à Part-Dieu', 'https://cyclopolis.lavilleavelo.org/vl10/VL10_Meyzieu_PartDieu.pdf'),
  (234, 'Voie Lyonnaise 11 - Bonnel – Dauphiné', 'velo', 'Dossier de concertation VL11 - Bonnel à Dauphiné', 'https://cyclopolis.lavilleavelo.org/vl11/VL11_Bonnel_Dauphin%C3%A9.pdf'),
  (235, 'Voie Lyonnaise 11 - Chassieu', 'velo', 'Dossier de concertation VL11 - Chassieu', 'https://cyclopolis.lavilleavelo.org/vl11/VL11_Chassieu.pdf'),
  (236, 'Voie Lyonnaise 12 - Valmy – Bron', 'velo', 'Dossier de concertation VL12 - Valmy à Bron', 'https://cyclopolis.lavilleavelo.org/vl12/VL12_Valmy_Bron.pdf');
